### PR TITLE
Determine which monitor the device is closest to based on RSSI value.

### PR DESCRIPTION
**Pull request by shbatm**
This PR includes:

1) Posting JSON info from the monitor into the attributes for the confidence sensor in HASS.
2) Posting the RSSI value (if present) into the attributes for the confidence sensor.
3) Posting the monitor location with the greatest RSSI value as `nearest_monitor` in the device's sensor attributes.
4) Renaming some variables to make it more clear what they are.

### CODE REVIEW

**Comment by Odianosen25** [comment]
Thanks for these @shbatm,

Your PRs are so valid, I just haven’t had time to test and merge. Will definitely create time within the next few days to merge, as this app getting traction now for some strange reasons and your PRs really makes it better.

Kind regards

**Comment by Odianosen25** [comment]
@shbatm,

I am trying to merge all your changes pls, but I am having a lot of conflicts. Will you be available to assist in resolving these? I could do them, but it will be merged unto yours, and I don't think will be nice messing with your code. At the same time, I have created a dev branch, and working on restructuring the repository to make it easier for use in HACS.

Kind regards

**Comment by shbatm** [comment]
Yep. I'll take a look when I get a chance. I may already have a merged copy I just need to update this branch with.

**Comment by Odianosen25** [comment]
@shbatm,

Thanks for the replay. Don't worry I have downloaded a local copy, which I have merged most of them. I will upload that to the master branch, and that should reduce the conflicts. 

If I need any other few chances, will let you know.

Kind regards

**Comment by Odianosen25** [comment]
@shbatm,

The conflicts was to many, so as I said I downloaded the file and added most of your changes. If you don't mind, can you resubmit the PR if you don't mind, so it takes not of these upgraded changes?

I made a few changes to yours and added some features I have been lazy all these while to add. The most noticeable breaking changes I made, if you decide to use this upgrade were:

- Changed `ad_scan_now` to `run_scan`. So now it supports even the rssi scanning from that topic
- I removed the `monitor` name that was appended to the entities generated in AD. Left HA as is

Do let me know if any other things, and if there is something you will like added. I think you will like this upgrade as I have added service calls, and the ability to reboot the hardware itself instead of just script. As its known even sometimes restarting the script alone, doesn't solve the issue of monitor not responding after a while.

Regards

**Pull request closed without merging**
