### PR TITLE
MQTT_MESSAGE Fix, Use RSSI scan, Code Cleanup

### LINKED ISSUE #1: Wrong message type for MQTT Listener:  MQTT instead of MQTT_MESSAGE
Hello! I am trying to implement your new script in ADv4, but I'm struggling to get it running as posted. 

Specifically, I wasn't getting any feedback from the MQTT service (publish was working fine, the subscription wasn't receiving any events).  Changing the [following line](https://github.com/Odianosen25/Monitor-App/blob/33a4ca0519c232715c3e965059713675c9f90a3d/home_presence_app.py#L63):
```python
        self.mqtt.listen_event(self.presence_message, 'MQTT', wildcard = '{}/#'.format(self.presence_topic))
```
to this:
```python
        self.mqtt.listen_event(self.presence_message, 'MQTT_MESSAGE', wildcard = '{}/#'.format(self.presence_topic))
```
seems to solve the issue.

### PR DESCRIPTION
**Pull request by shbatm**
Hello!  First of all, awesome app, this is exactly what I needed to tie together my Monitor nodes. 

I was a little bored (and a lot OCD) and did some code clean-up to make everything a bit more readable for myself so I could eventually expand this to include exterior motion sensors that trigger an Arrive scan after a delay (e.g. when my Hikvision camera detects a line crossing as my car approaches down the driveway).

I just wanted to share in case you were interested in incorporating any of the cleanups and tweaks. If not, no worries and thanks for the head start!

Changes:
- Change "MQTT" to "MQTT_MESSAGE" to fix #1 in the newest version of AppDaemon.
- Change `scan/arrive` to `scan/rssi` for the RSSI scan.
- Remove redundant checks to make sure a state has changed in Hass before changing.
- Black Formatting
- Cleanup of `presence_message` function for readability.
- Allow renaming of global sensors in the config (e.g. if you use other presence methods for "Everyone is Home")
- Renamed `apps.yaml` to `apps.yaml.sample` and ignore `apps.yaml` to allow `git pull` updates without conflict/overwriting the users' config file.
- Handle `presence_topic` with an additional `/` in the topic.

### CODE REVIEW

**Comment by Odianosen25** [comment]
Wow thanks for this @shbatm,

As I am just seeing this, will take a while to process it and get back to you.

I am not a full time programmer, so forgive me if I need some tutorial on what your changes and why.

Regards

**Comment by Odianosen25** [comment]
I tried running yours in my environment and got a lot of errors.

Will need to walk thru it later once I got some time at hand.

Regards

**Comment by shbatm** [comment]
Finally got around to testing this in detail and think I found most of the bugs you saw.  I screwed up and marked several callback functions with `**kwargs` instead of `kwargs`.

**Comment by Odianosen25** [comment]
Hello @shbatm,

Oh thanks for this. Will look into the new changes and get back if I got other questions.

Kind regards

**Comment by shbatm** [comment]
No problem. I really appreciate all the work you put into putting this together; going through it and putting my OCD to work really just helped me learn how AppDaemon works and interacts with HA. Feel free to use what you want out of my changes or disregard completely, just wanted to share back.

I'll also send a separate PR with a different branch that pushes the RSSI values to the confidence sensors' attributes and determines which device it was closest to.

**Comment by Odianosen25** [comment]
This is really good stuff, thanks again and will put some work into testing, hopefully this weekend.

Kind regards

**Pull request closed without merging**
